### PR TITLE
Fix edit profile commands and features

### LINKED ISSUE #148: [PE-D] Different error message
-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: yujinyang1998/ped#3

### LINKED ISSUE #153: [PE-D] Limit for some values are too large
Consider shrinking these limits

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: yujinyang1998/ped#8

### LINKED ISSUE #156: [PE-D] Issue regarding BMI calculation due to invalid height.
Although the user is reminded to enter height in m, it will still accept if the user enter the height in cm. This causes the BMI calculation to be 0. Not sure if there is anyway to prevent this.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: yuen-sihao/ped#3

### LINKED ISSUE #170: [PE-D] Nested user inputs - Not optimised for fast typists
The use of nested inputs for edit components of the profile function not optimised for fast typing.
Suggestion: could use delimiter to smoothen the process eg change name /to John Doe

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Johnson-Yee/ped#3

### PR DESCRIPTION
**Pull request by gohsonghan98**
changes:
1. edit commands are now one-shot
2. format printed if given invalid edit input
3. range restriction for age and height and weight

### CODE REVIEW

File: src/main/java/fitr/user/User.java [hunk 1]
```diff
@@ -123,66 +131,120 @@ public void setFitnessLevel(int userFitnessLevel) {
...
+                }
+                if (ageInput < 1 || ageInput > 130) {
                     Ui.printCustomError(ERROR_INVALID_AGE_INPUT);
+                    if (edit) {
+                        Ui.printCustomError("FORMAT: " + FORMAT_EDIT_AGE + LINE_BREAK + RANGE_EDIT_AGE);
+                        return;
+                    }
                     Ui.printCustomMessage(INPUT_AGE);
+                    Ui.printCustomError(RANGE_EDIT_AGE);
                 }
```
Comment (jerichochua) [inline src/main/java/fitr/user/User.java]: Can consider extracting this out as a method?

File: src/main/java/fitr/user/User.java [hunk 2]
```diff
@@ -123,66 +131,120 @@ public void setFitnessLevel(int userFitnessLevel) {
...
+                }
+                if (heightInput < 0.50 || heightInput > 4.00) {
                     Ui.printCustomError(ERROR_INVALID_HEIGHT_INPUT);
+                    if (edit) {
+                        Ui.printCustomError("FORMAT: " + FORMAT_EDIT_HEIGHT + LINE_BREAK + RANGE_EDIT_HEIGHT);
+                        return;
+                    }
+                    Ui.printCustomError(RANGE_EDIT_HEIGHT);
                     Ui.printCustomMessage(INPUT_HEIGHT);
                 }
```
Comment (jerichochua) [inline src/main/java/fitr/user/User.java]: Can consider extracting this out as a method?

File: src/main/java/fitr/user/User.java [hunk 3]
```diff
@@ -123,66 +131,120 @@ public void setFitnessLevel(int userFitnessLevel) {
...
+                }
+                if (weightInput < 2.00 || weightInput > 1000.00) {
                     Ui.printCustomError(ERROR_INVALID_WEIGHT_INPUT);
+                    if (edit) {
+                        Ui.printCustomError("FORMAT: " + FORMAT_EDIT_WEIGHT + LINE_BREAK + RANGE_EDIT_WEIGHT);
+                        return;
+                    }
+                    Ui.printCustomError(RANGE_EDIT_WEIGHT);
                     Ui.printCustomMessage(INPUT_WEIGHT);
                 }
```
Comment (jerichochua) [inline src/main/java/fitr/user/User.java]: Can consider extracting this out as a method?

File: src/main/java/fitr/user/User.java [hunk 4]
```diff
@@ -193,17 +255,29 @@ public void setupGender() {
...
+                    fitnessLevelInput = Integer.parseInt(Ui.read());
+                }
                 if (fitnessLevelInput != 0 && fitnessLevelInput != 1 && fitnessLevelInput != 2) {
+                    Ui.printCustomError(ERROR_INVALID_FITNESS_INPUT);
+                    if (edit) {
+                        Ui.printCustomError("FORMAT: " + FORMAT_EDIT_FITNESS);
+                        return;
+                    }
                     Ui.printCustomMessage(INPUT_FITNESS_LEVEL);
                 }
```
Comment (jerichochua) [inline src/main/java/fitr/user/User.java]: Can consider extracting this out as a method?

**Review by jerichochua — CHANGES_REQUESTED** [review]

**Review by jerichochua — APPROVED** [review]
